### ISSUE TITLE
"classified by others bug"

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/Manual-Classify#1]
Yesterday Heidi  and Emily logged in as Heidi and tried using the "classified by others" option from the drop down menu in manual classify, and we saw nothing. We should have been seeing something "classified by Emily", we think. 

I haven't yet tried being logged in as Emily and using the feature, as no one else has done any classifications yet.

**Comment by LouisK130** [comment]
This should be resolved as of a day or two ago.
