### ISSUE TITLE
allow more than one tag feature

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/Manual-Classify#2]
We had discussed that having the ability to apply more than one tag. Currently this is not an option. Is it on your "to do" list already.

**Comment by LouisK130** [comment]
A target can have as many tags as you want, they just have to be applied one at a time. If you tag, then save updates, then tag as something else and save again, both tags will be saved. Is it important that you can apply multiple in the same operation?

**Comment by eepeacock** [comment]
No, that is not important to apply 2 at once. Maybe I just didn't  
understand they were both being logged.

Thanks.


Quoting Louis Kilfoyle <notifications@github.com>:
