### ISSUE TITLE
python 3.4 compatibility

### ISSUE THREAD

**Issue by joefutrelle** [LouisK130/Manual-Classify#21]
For deployment purposes I would like to use Debian Jessie which ships with Python 3.4, however the following line in `views.py` uses a syntax that is not supported in 3.4:

```python
result = json.dumps({**{**result1, **result2}, **result3})
```

can this be rewritten to not use syntactic features added after 3.4?

**Comment by joefutrelle** [comment]
Also in utils.py

```python
targets = {**targets, **new_targets}
```

which I think is easier to fix ...

**Comment by LouisK130** [comment]
Both lines should be easily made compatible with 3.4. Again, I'm not really well equipped to make any commits right now, but the required changes are pretty minimal. See link below.

https://stackoverflow.com/questions/38987/how-to-merge-two-dictionaries-in-a-single-expression

**Comment by joefutrelle** [comment]
In addition, there are circular imports between database and utils, which could be addressed via refactoring.

**Comment by joefutrelle** [comment]
Pardon my denseness, but is there a difference between

```python
result = json.dumps({**{**result1, **result2}, **result3})
```

and

```python
result = json.dumps({**result1, **result2, **result3})
```
?

**Comment by LouisK130** [comment]
No. I think initially it was only `result1` and `result2` and when I added `result3` I was too lazy to test if I that syntax worked with more than 2 dicts.

**Comment by joefutrelle** [comment]
Got it, then this is an easy fix, thanks.
