### ISSUE TITLE
Bug with displaying images occasionally

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/Manual-Classify#38]
Why does this happen? Sometimes it is just a delay in loading. Sometimes they never load. I am in batch classify mode. 

![image](https://user-images.githubusercontent.com/14059636/40200772-24f784bc-59eb-11e8-99f4-d2977a21c9e4.png)

**Comment by LouisK130** [comment]
I believe this is now resolved. Please reopen if it continues to happen.
