### ISSUE TITLE
Batch mode bin filtering no longer well defined

### ISSUE THREAD

**Issue by LouisK130** [LouisK130/Manual-Classify#41]
With the introduction of on the fly annotation ordering, batch mode filtering (by assuming that power should be used to order the annotations) is no longer performing as desired. Bins that only contain most-recent annotations in the batch class (and no most-powerfuls) are filtered out and never displayed. I can only think of a few options, but I'm open to brainstorming:

1. Disable filtering entirely. I briefly tested this and it doesn't seem like a good answer. Users spend minutes just sifting through "empty" bins.

2. Filter based on having ANY annotations in the batch class (even if they aren't most-powerful or most-recent). This would guarantee you never miss any bins that have relevant annotations, but might also mean you view "empty" bins, depending on your ordering settings. I think this is probably the best temporary solution.

3. Require the ordering to be set up-front for batch mode. Filtering could then be done based on this decision, and safely be assumed to be accurate for the remainder of the session.

In v2, batch mode will no longer limit you to 1 class/tag combination. You can specify arbitrarily many. This further complicates the filtering process. It may be possible to do the filtering in Javascript (and delay the zip downloads until after we have determined that a bin is good), but this would likely result in slower load times.

**Comment by hsosik** [comment]
My initial thought is that number 3 makes fine sense. Emily would that work for your use case with Gedeon?

**Comment by eepeacock** [comment]
Hi, yes, I somehow missed this and just thought it was broken. I think option 3 would be best for now.

**Comment by LouisK130** [comment]
I've gone ahead and pushed a quick implementation of the third choice. You'll now specify the ordering you want to use when you're choosing batch mode settings. I only tested briefly, so please let me know if it isn't working as desired.

**Comment by joefutrelle** [comment]
this is deployed.

**Comment by eepeacock** [comment]
Okay, I'm trying to test batch mode:
January 1, 2006-December 31 2006
Most recent
Chaetoceros peruvianis (117)
ALL

Begin classifying Raw.

Does this work for you? I tried "shift reload" and tried again.
I got server error 500. I am 99% sure that Gedeon has put ROIs in that  
category.




Quoting Joe Futrelle <notifications@github.com>:

**Comment by LouisK130** [comment]
I just entered all those settings on the live version and it seems to work fine for me. I see the classification screen, and it lists Gedeon's annotations as the most powerful.

https://puu.sh/ANwmB/43ff6e71f0.png

**Comment by joefutrelle** [comment]
We're getting 500s. I'm seeing `ERROR:root:Unknown ordering option:` in the server logs. Then the app crashes because `bins` is `None` on line 155 of views.py

**Comment by LouisK130** [comment]
Fixed an issue in the most recent commit that I suspect is what you were experiencing. Were you seeing at least one loaded page before the 500? It shouldn't have been a problem until you tried to navigate to the second set of bins.

**Comment by eepeacock** [comment]
I was not seeing any loaded bins. But, I think Joe hasn't gotten to  
implement the most recent update yet. So, we'll try it.


Quoting Louis Kilfoyle <notifications@github.com>:

**Comment by eepeacock** [comment]
Okay, Joe just deployed the latest fixes and I couldn't get it to  
work. I am trying to batch classify chaetoceros in 2007 or 2008 for  
the MVCO time series. We tried logged in as me or Gedeon, and we tried  
shift+reload. Also we tried with most recent or most powerful selected.





Quoting Louis Kilfoyle <notifications@github.com>:

**Comment by eepeacock** [comment]
Hi- can you think of any other ideas for making batch mode work again?  
Currently if I choose a set of bins that I know have annotations for a  
given category it says "No specified bins have annotations in that  
batch class."





Quoting Louis Kilfoyle <notifications@github.com>:

**Comment by LouisK130** [comment]
This was also a symptom of the recent timeseries label change from "http" to "https" and should be resolved by 5f62bc4.
