### ISSUE TITLE
"add view" broken for manual results?

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/Manual-Classify#93]
It seems that add views only works now if you import autoclassifier results. 

Was that deliberate? or a bug? It is not a show stopper at the moment, but I thought it would work just with manual results as well.

**Comment by LouisK130** [comment]
Please explain how it is currently behaving, how you expect it to behave, and how to reproduce the problem, including explicit steps and values used (e.g. bins and views selected).

**Comment by eepeacock** [comment]
ugh. CLosing the issue. I got fooled by the "db" timeseries again. Sorry. 
Joe, can we get rid of these please?

**Comment by joefutrelle** [comment]
Done.
